### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [MaxShek/Skill14#1]
This is submitted for the helper methods project, but doesn't look like the code for it.

**Comment by chrisvfritz** [comment]
This is looking much better, though there is one change I'd like you to make, detailed below.

### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).

**Comment by MaxShek** [comment]
Should be changed!

**Comment by chrisvfritz** [comment]
:+1: Wonderful!
